@extends('admin.layout')
@section('title','Setup')
@section('content')
<h1>Hotel setup</h1>
<section class="panel"><h2>Room types</h2>@foreach($roomTypes as $type)<form class="grid" method="post" action="{{ route('admin.setup.room-types.update',$type) }}">@csrf<div><strong>{{ $type->name }}</strong><p class="muted">{{ $type->code }}</p></div><label>Base rate<input type="number" step="0.01" min="0" name="base_rate" value="{{ $type->base_rate }}"></label><label>Max adults<input type="number" min="1" name="max_adults" value="{{ $type->max_adults }}"></label><label>Max children<input type="number" min="0" name="max_children" value="{{ $type->max_children }}"></label><label><span>Active</span><input type="checkbox" name="is_active" value="1" @checked($type->is_active)></label><div><button>Save {{ $type->name }}</button></div></form><hr>@endforeach</section>
<section class="panel"><h2>Physical rooms & maintenance blocks</h2><form class="grid" method="post" action="{{ route('admin.setup.rooms.store') }}">@csrf<label>Room type<select name="room_type_id" required>@foreach($roomTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label><label>Room number<input name="number" required></label><label>Floor<input name="floor"></label><div><button>Add room</button></div></form><p class="muted">Current rooms: {{ $rooms->pluck('number')->join(', ') ?: 'none' }}</p><hr><form class="grid" method="post" action="{{ route('admin.setup.room-blocks.store') }}">@csrf<label>Room<select name="room_id">@foreach($rooms as $room)<option value="{{ $room->id }}">{{ $room->number }} · {{ $room->roomType->name }}</option>@endforeach</select></label><label>From<input type="date" name="starts_on" required></label><label>Until (checkout-style end)<input type="date" name="ends_on" required></label><label>Reason<input name="reason"></label><div><button>Block room</button></div></form>@foreach($roomBlocks as $block)<p>Room {{ $block->room->number }} · {{ $block->starts_on->format('d M Y') }} → {{ $block->ends_on->format('d M Y') }} · {{ $block->reason }} <form style="display:inline" method="post" action="{{ route('admin.setup.room-blocks.close',$block) }}">@csrf<button type="submit">Close block</button></form></p>@endforeach</section>
<section class="panel"><h2>Rate plans & dated rates</h2><form class="grid" method="post" action="{{ route('admin.setup.rate-plans.store') }}">@csrf<label>Name<input name="name" required></label><label>Code<input name="code"></label><label><span>Breakfast included</span><input type="checkbox" name="includes_breakfast" value="1"></label><div><button>Add rate plan</button></div></form><hr><form class="grid" method="post" action="{{ route('admin.setup.room-rates.store') }}">@csrf<label>Room type<select name="room_type_id">@foreach($roomTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label><label>Rate plan<select name="rate_plan_id">@foreach($ratePlans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></label><label>From<input type="date" name="starts_on" required></label><label>To<input type="date" name="ends_on" required></label><label>Nightly rate<input type="number" step="0.01" min="0" name="nightly_rate" required></label><label>Min stay<input type="number" min="1" name="min_stay" value="1" required></label><label>Max stay<input type="number" min="1" name="max_stay"></label><div><button>Add dated rate</button></div></form></section>
<section class="panel"><h2>Tax rules</h2><form class="grid" method="post" action="{{ route('admin.setup.tax-rules.store') }}">@csrf<label>Name<input name="name" required></label><label>Applies to<select name="applies_to"><option value="hotel">Hotel</option><option value="restaurant">Restaurant</option><option value="all">All</option></select></label><label>Rate %<input type="number" step="0.0001" min="0" max="100" name="rate_percent" required></label><label>Effective from<input type="date" name="effective_from"></label><label>Effective to<input type="date" name="effective_to"></label><div><button>Add tax rule</button></div></form></section>
<section class="panel"><h2>Restaurant setup</h2><form class="grid" method="post" action="{{ route('admin.setup.restaurant-categories.store') }}">@csrf<label>Category name<input name="name" required></label><div><button>Add category</button></div></form><hr><form class="grid" method="post" action="{{ route('admin.setup.restaurant-menu-items.store') }}">@csrf<label>Category<select name="restaurant_category_id">@foreach($restaurantCategories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Item name<input name="name" required></label><label>Price<input type="number" step="0.01" min="0" name="price" required></label><label><span>Vegetarian</span><input type="checkbox" name="is_vegetarian" value="1"></label><div><button>Add menu item</button></div></form><hr><form class="grid" method="post" action="{{ route('admin.setup.restaurant-tables.store') }}">@csrf<label>Code<input name="code" required></label><label>Name<input name="name" required></label><label>Capacity<input type="number" min="1" name="capacity"></label><div><button>Add table</button></div></form></section>
@endsection
